Repository DhanushNehru/Ultimate-DevOps-Resources, pull requests merged in 2023-10, with the labels that each got.

#3 Update README.md
  README.md
Labels: hacktoberfest-accepted

#9 Update README.md for YT channles
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#10 Added YouTube channel resources
  README.md
  Yt_channels.md
Labels: hacktoberfest, hacktoberfest-accepted

#23 Add Ultimate-DevOps-Resources
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#27 Added DevOps Tools section
  README.md
Labels: hacktoberfest, hacktoberfest-accepted
